### ISSUE TITLE
Done button is always active on Wishlist to Reading popup

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#11]

**Comment by dletk** [comment]
I see there are 2 things need to be done with this Done button.
1. It is in destructive configuration, I do not find any where that say exactly what configuration it should be, but I think Done button should just be Default configuration.
2. We can allow user to leave the textField blank, it that case, we will default the value for total pages and current page to be 0. 
I will implement these things and show it to you guys in class
