### ISSUE TITLE
Changing the status (reading/WL/Complete) not completely intuitive

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#16]
The first thing users do when they try to change the status of a book is tap on it and are surprised that there is not a button at the bottom that allows you to move it to a different tab or delete it. They do not initially resort to swiping, but eventually after messing around for a bit can figure it out. The suggestion was to include a bottom of the BookViewController saying "Move to ____"

**Comment by dletk** [comment]
I think we can have a switch with the label is" reading". If it is on (green), it means that they are reading it, it is is off then the book is in completed list or wishList.

**Comment by spencermg3** [comment]
I don't think I understand what your suggestion is. Are you saying we have a little on/off slider thing that tells us whether they are reading or not? If we do that I'm not sure if it would be intuitive for them what happens when you switch it from on (reading) to off (not reading). I was thinking we have buttons at the bottom saying "Mark as ___" or "Delete" or something like that

**Comment by dletk** [comment]
I think that this problem can be solved completely if we have the tutorial at the beginning. Since I suspect that adding any slider/button into our view not really a good choice for the designing and aesthetic work.

**Comment by spencermg3** [comment]
This is solved by adding a tutorial
