### ISSUE TITLE
Progress Sorting not completely intuitive

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#17]
Users were a little confused because we do not give a number for % complete, so they assume that it is supposed to sort by current page number. One person said it would help to give the percentage so that they could see it

**Comment by dletk** [comment]
I agree on this idea, since it is hard for me as well to see the difference. Having a small label showing the percentage can be very useful.

**Comment by spencermg3** [comment]
yeah, I think if we include the percentage, even if it is small, it would be much more obvious and I think it would be doable since we do have a lot of room on that section of the cell

**Comment by spencermg3** [comment]
I can work on this one right now. So did we decide that we want it in increasing order (0% at the top and 100% at the bottom) or the other way around (100% at the top and 0% at the bottom)? I was thinking the more complete books should be at the top since those are the ones that the user is currently reading most frequently and those would be the books that the user most likely would want to read, especially if they are very close to being done and just want to finish it off. But I am open to either way, and I can ask people in user testing as well. Do either of you have a particular preference?

**Comment by dletk** [comment]
I think this is Kelli's work. Since she is working on re-design the view, and she is familiar with how the constraint is being set up in the cell.

**Comment by dletk** [comment]
Also, we haven't talked about this in depth, so we can consider it more tonight.

**Comment by spencermg3** [comment]
Sounds good! Just something to think about but yes, we can talk about it more tonight

**Comment by dletk** [comment]
@kellimandel  solved this problem by adding the percent label next to the progress bar in the table cell.
