### ISSUE TITLE
Unclear what the color selector means

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#18]
The PF was confused as to what exactly it does. The other two people I had test it were able to figure it out very quickly. One person, though, asked what it does and was expecting for it to have some functionality. He suggested adding another sorting option to sort by color so that if users want to, they would have the option to use the colors to sort by genre or, really, however they want to utilize it

**Comment by dletk** [comment]
I really like the sorting by genre/ colors idea. Since I figure out that can be very useful when users try to do some sort of organizing on the own.
