### ISSUE TITLE
Make a tutorial scene on first use

### ISSUE THREAD

**Issue by dletk** [dletk/BookIt#19]
On the process of researching for the problem with users not know about how to use the swipe function, I see some examples that we can make a tutorial scene, only appear on the first time the app is launched, that displays a simple picture showing that user can swipe left and right to interact with the book. I believe that this will solve many of our solution.

**Comment by dletk** [comment]
Something like this

![image](https://cloud.githubusercontent.com/assets/16824485/25216477/7b4e54ca-2568-11e7-8284-9030a152d715.png)

**Comment by spencermg3** [comment]
I like this, I think that would look good and I remember the PF who tested it mentioning that it would be helpful for him to have

**Comment by dletk** [comment]
Solved!
