### ISSUE TITLE
SegmentedControl on ReadingBooksTableViewController too crowded

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#20]
The color sort allows the user to sort books by their icon color (I figure the order of the colors doesn't matter so I just made it easy and did it alphabetically: Red --> Purple --> Green --> Gold --> Blue). We won't want to keep this as it is because we will not want to have five sorting options for the reading books. I was thinking we could just have one option for "% Complete" rather than two different options for sorting by progress. What would you think about that?

**Comment by dletk** [comment]
Personally, I think we can go with the option that only keep 1 sorting filter for progress, which is "% Completed". And I believe that we should keep it in the order from lowest - highest. Since some of the book will not have the total number of pages entered, they will be shown on top by that way.

**Comment by kellimandel** [comment]
Yeah, I agree that all the sort functions look crowded. Simplifying the progress filters into 1 sounds like a good idea to me!

**Comment by dletk** [comment]
I think you @spencermg3  should work on this one.

**Comment by spencermg3** [comment]
Isn't this the same thing as Issue #17?

**Comment by spencermg3** [comment]
I can certainly work on this if you want, but solving this issue seems to inherently solve issue #17

**Comment by dletk** [comment]
No it is different. Issue #17 is solved by adding a percentage label next to the progress bar. This issue is about eliminating 1 of the sorting filter.

**Comment by spencermg3** [comment]
Oh sorry, I guess this is the issue I was getting at in the other thread when I was asking whether we want increasing progress or decreasing

**Comment by dletk** [comment]
#17  is more about adding UI stuff, and this one you need to work with the code as well since you are getting rid of one FilterType

**Comment by dletk** [comment]
No worry. So you are ok to work on this?

**Comment by spencermg3** [comment]
I can certainly work on this. But I just wanted to check in if you had a particular preference on which way I order it and thought I would provide my input

**Comment by spencermg3** [comment]
Are you fine with me starting with highest % at the top and lowest % on the bottom, so doing it in decreasing order?

**Comment by dletk** [comment]
How about letting it sort from higher percentage to lower first, and we can decide later. I think it won't be hard for you to change.
