### ISSUE TITLE
Having author name in ReadingScene

### ISSUE THREAD

**Issue by dletk** [dletk/BookIt#21]
I think that because we are having author's name in the other 2 scenes, it should be included in the Reading Scene as well, so our app will have a consistent theme.

**Comment by dletk** [comment]
Also, because we have the option to sort by author's name, it will be unclear if the results show up since there is a match in author's name, but users do not see why they show up like that.

**Comment by kellimandel** [comment]
I agree. I think the author's name is probably an important piece of information for the user to see.
