### ISSUE TITLE
When you look at the Info for a Completed Book, it shows the Current Page and Total Pages

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#22]

**Comment by spencermg3** [comment]
I noticed this and wasn't too sure if we had decided on what to do with this. Is this what we want, or should we talk about it?

**Comment by dletk** [comment]
I do not understand what you are saying here?? Can you explain it a little bit more detailed?

**Comment by spencermg3** [comment]
Well if you go to a completed book and tap on it, it gives you the Book's information. With the WishList we decided we only wanted to show the title, author, and color. I was wondering what your thoughts would be on doing the same thing with a completed book. Since we probably don't need to know the current page of a book if we are done reading it. So I was thinking maybe only show the total number of pages and get rid of the current page for completed books?

**Comment by dletk** [comment]
Oh I see, we can talk about it for sure, it is not a hard feature for me to add.

**Comment by spencermg3** [comment]
For example, suppose I am reading a book. This book has 100 pages. Last time I read it, I got to page 75. So I pick it up and finish reading it and mark it as done without updating the current page number, since I am done and updating my current page to 100 doesn't really do anything for me. But if I mark it as done and look at the details, it will say I am on page 75

**Comment by spencermg3** [comment]
Yeah it shouldn't be too hard to add, just a matter of figuring out what would be the most useful

**Comment by dletk** [comment]
Solved!
