### ISSUE TITLE
Search Bar in History tab remains active after switching to a different tab

### ISSUE THREAD

**Issue by spencermg3** [dletk/BookIt#7]
When you tap on the search bar in "History" and go from "History" to "Reading" and back to "History", the search bar will be in its active state when you re-open the "History" tab

**Comment by dletk** [comment]
SOLVED ----> In the method viewWillDisappear of CompletedBooksViewController, I have called searchController.isActive = false, so whenever this tab is switched to new tab, the searchBar will be inactive.
